import React, { useContext } from 'react';
import { AppContext } from '../context/AppContext';

const Gallery = () => {
    const { galleryImages } = useContext(AppContext);

    return (
        <div className="my-16 text-center">
            <h2 className="text-3xl font-semibold mb-2">Community Gallery</h2>
            <p className="text-gray-500 mb-8">Explore recent masterpieces generated by our users worldwide</p>

            {galleryImages.length === 0 ? (
                <p className="text-gray-400">No images generated yet. Be the first!</p>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 px-6 max-w-6xl mx-auto">
                    {galleryImages.map((img) => (
                        <div key={img._id} className="bg-white rounded-xl shadow-md overflow-hidden border border-gray-100 p-3 hover:scale-105 transition-transform duration-300">
                            <div className="relative group">
                                <img
                                    src={img.resultImage}
                                    alt={img.prompt}
                                    className="w-full h-64 object-cover rounded-lg"
                                    loading="lazy"
                                />
                            </div>
                            <div className="mt-3 flex items-center justify-between">
                                <div className="text-left">
                                    <p className="text-sm font-medium text-gray-800 line-clamp-1">"{img.prompt}"</p>
                                    <p className="text-xs text-gray-400 mt-1">By: {img.authorName || 'Anonymous'}</p>
                                </div>
                                {/* Download Button */}
                                <a
                                    href={img.resultImage}
                                    download={`${img.prompt.replace(/\s+/g, '_')}.png`}
                                    className="p-2 bg-gray-100 hover:bg-gray-200 rounded-full transition-colors duration-200"
                                    title="Download Image"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4 text-gray-600">
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                                    </svg>
                                </a>
                            </div>
                            <div className="mt-3 text-left">
                                <p className="text-sm font-medium text-gray-800 line-clamp-1">"{img.prompt}"</p>
                                <p className="text-xs text-gray-400 mt-1">By: {img.authorName || 'Anonymous'}</p>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default Gallery;